[env:kwest_nRF52840_black]
board_level = extra
extends = nrf52840_base
board = nordic_pca10059
build_flags = ${nrf52840_base.build_flags} 
  -I variants/kwest_nRF52840_black
  -D NORDIC_PCA10059
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/kwest/kwest_nRF52840_black>
lib_deps = ${nrf52840_base.lib_deps}
debug_tool = jlink
