; Seeed Xiao BLE: https://www.digikey.com/en/products/detail/seeed-technology-co-ltd/102010448/16652893
[env:kwest_xiao_ble]
extends = nrf52840_base
board = xiao_ble_sense
board_level = extra
build_flags = ${nrf52840_base.build_flags} 
  -I variants/kwest/kwest_xiao_ble 
  -I src/platform/nrf52/softdevice 
  -I src/platform/nrf52/softdevice/nrf52 
  -D  SEEED_XIAO_NRF52840_KIT 
  -D  GPS_L76K
  ; -D EBYTE_E22 
  ; -D EBYTE_E22_900M30S 
  ; -D PRIVATE_HW
  -D MESHTASTIC_EXCLUDE_ATAK=1
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -D MESHTASTIC_EXCLUDE_WEBSERVER=1
  -D MESHTASTIC_EXCLUDE_CANNEDMESSAGES=1
  ; -D MESHTASTIC_EXCLUDE_SCREEN=1

board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/kwest_xiao_ble>
lib_deps = 
  ${nrf52840_base.lib_deps}
debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
;upload_protocol = jlink
